//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buhler_TestApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buhler_TestApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in looking for nearest trucks.
        /// </summary>
        internal static string ErrorInLookingForNearestTrucks {
            get {
                return ResourceManager.GetString("ErrorInLookingForNearestTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        internal static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading app settings.
        /// </summary>
        internal static string ErrorReadingAppSettings {
            get {
                return ResourceManager.GetString("ErrorReadingAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing app settings.
        /// </summary>
        internal static string ErrorWritingAppSettings {
            get {
                return ResourceManager.GetString("ErrorWritingAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food item is not included in list of allowed. Call &quot;GetFoodItems&quot; for list of valid items.
        /// </summary>
        internal static string FoodItemIsNotValid {
            get {
                return ResourceManager.GetString("FoodItemIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food item is null or empty.
        /// </summary>
        internal static string FoodItemIsNullOrEmpty {
            get {
                return ResourceManager.GetString("FoodItemIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food truck request can not be null or empty.
        /// </summary>
        internal static string foodTruckRequest {
            get {
                return ResourceManager.GetString("foodTruckRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is out of allowed range from -90 to 90.
        /// </summary>
        internal static string LatitudeIsOutOfRange {
            get {
                return ResourceManager.GetString("LatitudeIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is out of allowed range from -180 to 180.
        /// </summary>
        internal static string LongitudeIsOutOfRange {
            get {
                return ResourceManager.GetString("LongitudeIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trucks for defined category found.
        /// </summary>
        internal static string NoTrucksForDefinedCategoryFound {
            get {
                return ResourceManager.GetString("NoTrucksForDefinedCategoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of required results have to been bigger then 0.
        /// </summary>
        internal static string ResultsCountIsOutOfRange {
            get {
                return ResourceManager.GetString("ResultsCountIsOutOfRange", resourceCulture);
            }
        }
    }
}
